#!/bin/zsh

cat <<EOF | ssh yagni -T
  mkdir -p $HOME/painkiller
  git clone https://github.com/cruftbusters/painkiller-layouts painkiller/layouts
  cd painkiller/layouts
  ln -s $HOME/painkiller/layouts/scripts/painkiller.layouts.service $HOME/.config/systemd/user/
  systemctl enable painkiller.layouts --user
EOF
