#!/bin/zsh

cat <<EOF | ssh yagni -T
  mkdir -p $HOME/painkiller
  git clone https://github.com/cruftbusters/painkiller-layouts painkiller/layouts-test
  cd painkiller/layouts-test
  git checkout test
  ln -s $HOME/painkiller/layouts-test/scripts/painkiller.layouts-test.service $HOME/.config/systemd/user/
  systemctl enable painkiller.layouts-test --user
EOF
